% TrainAutoencoder
IN = X; 
hiddenSize = 25;
autoenc = trainAutoencoder(IN, hiddenSize,...
        'MaxEpochs',100,...
        'EncoderTransferFunction','satlin',...
        'DecoderTransferFunction','purelin',...
        'L2WeightRegularization',0.01,...
        'SparsityRegularization',4,...
        'SparsityProportion',0.10);
    
% hiddenSize = 10;
% autoenc1 = trainAutoencoder(X,hiddenSize,...
%     'L2WeightRegularization',0.001,...
%     'SparsityRegularization',4,...
%     'SparsityProportion',0.05,...
%     'DecoderTransferFunction','purelin');

% autoenc = trainAutoencoder(X);
% net = network(autoenc);
% Xpred = net(X);
INreconstructed = predict(autoenc, IN);
mseError = mse(IN - INreconstructed);

figure;
plot(IN,'r.');
hold on
plot(INreconstructed,'go');

%[C, S, B] = regression(X, Xpred, 'one')
figure;
plotregression(IN, INreconstructed);